name: Java CI/CD On-Demand

on:
  workflow_dispatch:
    inputs:
      run_scan:
        description: 'Run security scan?'
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Workspace:"
          ls -la
          echo "mock-java-app:"
          ls -la mock-java-app

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('mock-java-app/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: mock-java-app
        run: mvn -B package

      - name: Run unit tests
        working-directory: mock-java-app
        run: mvn test

      - name: Run Checkstyle (conditional)
        if: ${{ inputs.run_scan }}
        working-directory: mock-java-app
        run: mvn checkstyle:check

      # OWASP Dependency Check with verified paths
      - name: Cache OWASP Dependency-Check data
        if: ${{ inputs.run_scan }}
        uses: actions/cache@v3
        with:
          path: ~/.dependency-check/data
          key: ${{ runner.os }}-owasp-data-${{ hashFiles('mock-java-app/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-owasp-data-

      - name: Verify OWASP cache path
        if: ${{ inputs.run_scan }}
        run: |
          echo "Cache path:"
          ls -la ~/.dependency-check/data || echo "No cache exists (normal first run)"

      - name: Run OWASP Dependency Check (conditional)
        if: ${{ inputs.run_scan }}
        working-directory: mock-java-app
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          # Explicitly set report format and location
          mvn org.owasp:dependency-check-maven:check \
            -DdependencyCheck.outputDirectory=target/owasp-reports \
            -DdependencyCheck.format=HTML \
            -DdependencyCheck.htmlReportName=report.html
          
          # Verify report generation
          echo "Generated reports:"
          ls -la target/owasp-reports/
        continue-on-error: true

      - name: Upload OWASP Report
        if: ${{ inputs.run_scan }}
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: mock-java-app/target/owasp-reports/report.html
          retention-days: 3
          if-no-files-found: error

  deploy:
    name: Deploy (Dummy)
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2

      - name: Verify AWS access
        run: aws sts get-caller-identity

      - name: Dummy deploy step
        run: echo "🚀 Deploying app from mock-java-app..."