name: Java CI/CD On-Demand

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      run_scan:
        description: 'Run security scan?'
        type: boolean
        default: false  # Default: Skip scan

permissions:
  id-token: write   # Required for AWS OIDC
  contents: read    # Required for actions/checkout

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('mock-java-app/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: mock-java-app
        run: mvn -B package

      - name: Run unit tests
        working-directory: mock-java-app
        run: mvn test

      - name: Run Checkstyle (conditional)
        if: ${{ inputs.run_scan }}
        working-directory: mock-java-app
        run: mvn checkstyle:check

      - name: Run OWASP Dependency Check (conditional)
        if: ${{ inputs.run_scan }}
        working-directory: mock-java-app
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn org.owasp:dependency-check-maven:check
        continue-on-error: true


  deploy:
    name: Deploy (Dummy)
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2

      - name: Verify AWS access
        run: aws sts get-caller-identity

      - name: Dummy deploy step
        run: echo "🚀 Deploying app from mock-java-app..."
