name: AWS OIDC Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Debug: Show exact repository structure
      - name: Debug repository contents
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          find . -type f | sort
          echo "Script contents:"
          cat ./scripts/get.sh || echo "Cannot read script"

      # Run tests (works whether script exists or not)
      - name: Execute tests
        run: |
          # Always verify AWS access first
          echo "=== AWS Identity ==="
          aws sts get-caller-identity
          
          # Try to run script if exists
          if [ -f "./scripts/get.sh" ]; then
            echo "=== Running custom script ==="
            chmod +x ./scripts/get.sh
            ./scripts/get.sh
          else
            echo "::warning::Custom script not found, running fallback commands"
            echo "=== IAM Roles ==="
            aws iam list-roles --query 'Roles[*].RoleName' --output text | tr '\t' '\n'
          fi