name: AWS OIDC Authentication

on:
  push:
    branches: [ main ]  # or your preferred branch
  
  # Optional: also trigger on pull requests
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Adds manual trigger option

permissions:
  id-token: write   # This is required for OIDC
  contents: read    # This is required for actions/checkout

jobs:
  auth-and-test:
    runs-on: ubuntu-latest
    steps:

      # MUST COME FIRST - Provides access to your repo files
      - uses: actions/checkout@v4      
      # 1. Configure AWS Credentials
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2

      # 2. Verification Steps
      - name: Verify AWS Access
        run: |
          echo "=== AWS Identity ==="
          aws sts get-caller-identity
          
          echo "=== S3 Buckets ==="
          aws s3 ls

      - name: Make script executable
        run: chmod +x ./scripts/get.sh  # ← Correct path

      # 3. Add your test steps here
      - name: Run Script
        run: ./scripts/get.sh

# jobs:
#   # call_reusable:
#   #   uses: marcoliew/reusable_gha_wf/.github/workflows/aws-oidc-auth.yml@main
#   #   secrets:
#   #     aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
#   auth:
#     uses: marcoliew/reusable_gha_wf/.github/workflows/aws-oidc-auth.yml@main
#     secrets:
#       aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}  # ← Secret passed correctly
#     with: # ← Regular inputs (non-secrets)
#       aws_region: ap-southeast-2 # Optional since default exists


