name: AWS OIDC Authentication

on:
  push:
    branches: [ main ]  # or your preferred branch
  
  # Optional: also trigger on pull requests
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Adds manual trigger option

permissions:
  id-token: write   # This is required for OIDC
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2
      - name: Verify AWS access by listing S3 buckets
        run: |
          # List all S3 buckets (simple verification)
          echo "=== Listing S3 buckets ==="
          aws s3 ls
          
          # Optional: More detailed verification
          echo "=== AWS caller identity ==="
          aws sts get-caller-identity
      
      # Your deployment steps here
