name: AWS OIDC Authentication

on:
  push:
    branches: [ main ]  # or your preferred branch
  
  # Optional: also trigger on pull requests
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Adds manual trigger option

permissions:
  id-token: write   # This is required for OIDC
  contents: read    # This is required for actions/checkout

jobs:
  # call_reusable:
  #   uses: marcoliew/reusable_gha_wf/.github/workflows/aws-oidc-auth.yml@main
  #   secrets:
  #     aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
  auth:
    uses: marcoliew/reusable_gha_wf/.github/workflows/aws-oidc-auth.yml@main
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}  # ← Secret passed correctly
    with: # ← Regular inputs (non-secrets)
      aws_region: ap-southeast-2 # Optional since default exists
  # secrets: inherit  # Or specify individual secrets

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4    # Required to access scripts

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
  #         aws-region: ap-southeast-2

  #     - name: Verify AWS access by listing S3 buckets
  #       run: |
  #         # List all S3 buckets (simple verification)
  #         echo "=== Listing S3 buckets ==="
  #         aws s3 ls
          
  #         # Optional: More detailed verification
  #         echo "=== AWS caller identity ==="
  #         aws sts get-caller-identity
      
  #     - name: Run deployment script
  #       run: chmod +x ./scripts/aws_deploy.sh && ./scripts/deploy.sh

