name: Deploy with Tags/Flags

on:
  push:
    branches: [placeholder]    # Trigger on commits to main
    tags: ['staging-*'] # Also trigger on staging-* tags

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run for branch pushes
    steps:
      - run: ./deploy-to-dev.sh

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: startsWith(github.ref, 'refs/tags/staging-')
    steps:
      - uses: actions/checkout@v4
      - name: Read deploy flag
        id: flags
        run: |
          ENABLED=$(jq -r '."enable-staging"' deploy-flags.json)
          echo "DEPLOY_ENABLED=$ENABLED" >> $GITHUB_OUTPUT
      - name: Deploy if enabled
        if: steps.flags.outputs.DEPLOY_ENABLED == 'true'
        run: ./scripts/deploy-to-staging.sh

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event_name == 'workflow_dispatch'  # Manual approval
    steps:
      - run: ./deploy-to-prod.sh